app:
  title: local Backstage 101

organization:
  name: My yyyy

backend:
  # This is for local development only, it is not recommended to use this in production
  # The production database configuration is stored in app-config.production.yaml
  database:
    # client: better-sqlite3
    # connection: ':memory:'
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
integrations:
  github:
    - host: github.com
      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
      # about setting up the GitHub integration here: https://backstage.io/docs/integrations/github/locations#configuration
      token: ${GITHUB_TOKEN}
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Local example data, file locations are relative to the backend process, typically `packages/backend`
    - type: file
      target: ../../examples/entities.yaml

    # Local example template
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    # - type: file
    #   target: ../../examples/template/template1.yaml
    #   rules:
    #     - allow: [Template]
    # - type: file
    #   target: ../../examples/template/template2.yaml
    #   rules:
    #     - allow: [Template]
    # Local example User Group
    - type: file
      target: ../../examples/group.yaml
      rules:
        - allow: [User, Group]
    # URL
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/backstage-group.yaml
    #   rules:
    #     - allow: [Group]

    # - type: url
    #   target: https://github.com/kongdev/poc-software-templates/blob/main/github-pages-site/template.yaml
    #   rules:
    #     - allow: [Template]
    - type: url
      target: https://github.com/backstage/software-templates/blob/main/scaffolder-templates/react-ssr-template/template.yaml
      rules:
        - allow: [Template]
    # Local example organizational data
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme/org.yaml
    #   rules:
    #     - allow: [User, Group]
    # - type: file
    #   target: ../../examples/group.yaml
    #   rules:
    #     - allow: [User, Group]
kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: ${K8S_MINIKUBE_URL}
          name: minikube
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: false
          serviceAccountToken: ${K8S_MINIKUBE_TOKEN}
auth:
  # omitIdentityTokenOwnershipClaim: true
  environment: development
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    keycloak:
      development:
        clientId: ${KC_CLIENT_ID}
        clientSecret: ${KC_CLIENT_SECRET}
        metadataUrl: ${KC_URL_CONFIG}
        prompt: auto
# RBAC configuration
permission:
  enabled: true
  rbac:
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
      - kubernetes
    policies-csv-file: ../../rbac-policy.csv
    policyFileReload: true
    admin:
      users:
        - name: user:user:default/vvip
        - name: group:default/dev
      superUsers:
        - name: user:user:default/vvip
        - name: group:default/dev
