# group.yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: The admin group
  namespace: default
spec:
  type: team
  profile:
    displayName: Admin Team
    email: admin@team.com
  children: []
  members:
    - user:default/kongdev
    - user:default/vvip
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev
  description: The developer group
  namespace: default
spec:
  type: team
  profile:
    displayName: Team dev 888
    email: dev@team.com
  children: [] # ถ้ามี subgroup ให้ใส่ชื่อที่นี่
  members:
    - user:default/vvip # คนในกลุ่ม
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra
  description: The infra group
  namespace: default
spec:
  type: team
  profile:
    displayName: Team infra 888
    email: infra@team.com
  children: [] # ถ้ามี subgroup ให้ใส่ชื่อที่นี่
  members:
    - user:default/kongdev # คนในกลุ่ม
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: kongdev
  namespace: default
spec:
  profile:
    displayName: kong dev
    email: vasin.nopaket@kingpower.com
  memberOf:
    - group:default/infra
    - group:default/admin
  annotations:
    backstage.io/managed-by-origin: keycloak
    backstage.io/user-email: vasin.nopaket@kingpower.com
    backstage.io/user-id: kongdev
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vvip
  namespace: default
spec:
  profile:
    displayName: vvip vip
    email: vvip@kingpower.com
  memberOf:
    - group:default/dev
    - group:default/admin
  annotations:
    backstage.io/managed-by-origin: keycloak
    backstage.io/user-email: vvip@kingpower.com
    backstage.io/user-id: vvip
